image: python:3.5
test:
  script:
    - pip install -r requirements.txt
    - coverage run test_tweet_analyser_input_params.py
    - coverage run --branch test_tweet_analyser_input_params.py
    - coverage report -m